### PR TITLE
feat: Add activesupport 8.0 support

### PR DESCRIPTION
**Pull request by bilby91**

### CODE REVIEW

**Comment by bilby91** [comment]
@mkon Not sure what you think about the change to the GitHub action, activesupport 8 doesn't support ruby 3.1. Happy to change the implementation.

**Comment by mkon** [comment]
Hey @bilby91, thanks for the PR 👍.
I think we should just drop support for ruby 3.1 since it is quite easy to upgrade ruby. This should keep the test matrix simple.

**Comment by bilby91** [comment]
@mkon Make sense. I wasn't sure if you wanted to remove it because is technically still supported. I think the tradeoff makes sense :).

Waiting for jobs to complete and should be ready for merging.

**Comment by mkon** [comment]
@bilby91 can you raise the `required_ruby_version` to 3.2+ in the gemspec?

**Comment by bilby91** [comment]
@mkon Done!

**Review by mkon — APPROVED** [review]
Great thanks :)

**Comment by bilby91** [comment]
@mkon Can you release a new version ?

**Comment by mkon** [comment]
I released 0.15.1 @bilby91

**Pull request merged**
